exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('drug').del().then(function() {
    // Inserts seed entries
    return knex('drug').insert([
      {
        "DRUGID": 1,
        "DRUGTYPE": "DRUGTYPE1",
        "DRUGNAME": "DRUGNAME1",
        "DOSE": 1,
        "TIER": 1,
        "HCCOST": 1,
        "COSTPERDOSE": 1,
        "PAYERID": 1
      }, {
        "DRUGID": 2,
        "DRUGTYPE": "DRUGTYPE2",
        "DRUGNAME": "DRUGNAME2",
        "DOSE": 2,
        "TIER": 2,
        "HCCOST": 2,
        "COSTPERDOSE": 2,
        "PAYERID": 1
      }, {
        "DRUGID": 3,
        "DRUGTYPE": "DRUGTYPE3",
        "DRUGNAME": "DRUGNAME3",
        "DOSE": 3,
        "TIER": 3,
        "HCCOST": 3,
        "COSTPERDOSE": 3,
        "PAYERID": 1
      }, {
        "DRUGID": 4,
        "DRUGTYPE": "DRUGTYPE4",
        "DRUGNAME": "DRUGNAME4",
        "DOSE": 4,
        "TIER": 4,
        "HCCOST": 4,
        "COSTPERDOSE": 4,
        "PAYERID": 1
      }, {
        "DRUGID": 5,
        "DRUGTYPE": "DRUGTYPE5",
        "DRUGNAME": "DRUGNAME5",
        "DOSE": 5,
        "TIER": 5,
        "HCCOST": 5,
        "COSTPERDOSE": 5,
        "PAYERID": 1
      }, {
        "DRUGID": 6,
        "DRUGTYPE": "DRUGTYPE6",
        "DRUGNAME": "DRUGNAME6",
        "DOSE": 6,
        "TIER": 6,
        "HCCOST": 6,
        "COSTPERDOSE": 6,
        "PAYERID": 1
      }, {
        "DRUGID": 7,
        "DRUGTYPE": "DRUGTYPE7",
        "DRUGNAME": "DRUGNAME7",
        "DOSE": 7,
        "TIER": 7,
        "HCCOST": 7,
        "COSTPERDOSE": 7,
        "PAYERID": 1
      }, {
        "DRUGID": 8,
        "DRUGTYPE": "DRUGTYPE8",
        "DRUGNAME": "DRUGNAME8",
        "DOSE": 8,
        "TIER": 8,
        "HCCOST": 8,
        "COSTPERDOSE": 8,
        "PAYERID": 1
      }, {
        "DRUGID": 9,
        "DRUGTYPE": "DRUGTYPE9",
        "DRUGNAME": "DRUGNAME9",
        "DOSE": 9,
        "TIER": 9,
        "HCCOST": 9,
        "COSTPERDOSE": 9,
        "PAYERID": 1
      }, {
        "DRUGID": 10,
        "DRUGTYPE": "DRUGTYPE10",
        "DRUGNAME": "DRUGNAME10",
        "DOSE": 10,
        "TIER": 10,
        "HCCOST": 10,
        "COSTPERDOSE": 10,
        "PAYERID": 1
      }, {
        "DRUGID": 11,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "rocephin",
        "DOSE": 500,
        "TIER": 2,
        "HCCOST": 276,
        "COSTPERDOSE": 249,
        "PAYERID": 2
      }, {
        "DRUGID": 12,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "cefepime",
        "DOSE": 500,
        "TIER": 3,
        "HCCOST": 350,
        "COSTPERDOSE": 53,
        "PAYERID": 2
      }, {
        "DRUGID": 13,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "zosyn",
        "DOSE": 1000,
        "TIER": 2,
        "HCCOST": 169,
        "COSTPERDOSE": 111,
        "PAYERID": 2
      }, {
        "DRUGID": 14,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "daptomycin",
        "DOSE": 500,
        "TIER": 4,
        "HCCOST": 267,
        "COSTPERDOSE": 230,
        "PAYERID": 2
      }, {
        "DRUGID": 15,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "invanz",
        "DOSE": 500,
        "TIER": 3,
        "HCCOST": 53,
        "COSTPERDOSE": 155,
        "PAYERID": 2
      }, {
        "DRUGID": 16,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "meropenem",
        "DOSE": 1000,
        "TIER": 4,
        "HCCOST": 362,
        "COSTPERDOSE": 99,
        "PAYERID": 2
      }, {
        "DRUGID": 17,
        "DRUGTYPE": "enternal_nutrition",
        "DRUGNAME": "ensure",
        "DOSE": 500,
        "TIER": 1,
        "HCCOST": 174,
        "COSTPERDOSE": 88,
        "PAYERID": 2
      }, {
        "DRUGID": 18,
        "DRUGTYPE": "enternal_nutrition",
        "DRUGNAME": "vivonex 10",
        "DOSE": 500,
        "TIER": 3,
        "HCCOST": 365,
        "COSTPERDOSE": 77,
        "PAYERID": 2
      }, {
        "DRUGID": 19,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "vancomycin",
        "DOSE": 500,
        "TIER": 2,
        "HCCOST": 286,
        "COSTPERDOSE": 43,
        "PAYERID": 3
      }, {
        "DRUGID": 20,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "rocephin",
        "DOSE": 500,
        "TIER": 2,
        "HCCOST": 276,
        "COSTPERDOSE": 67,
        "PAYERID": 3
      }, {
        "DRUGID": 21,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "cefepime",
        "DOSE": 500,
        "TIER": 3,
        "HCCOST": 350,
        "COSTPERDOSE": 188,
        "PAYERID": 3
      }, {
        "DRUGID": 22,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "zosyn",
        "DOSE": 1000,
        "TIER": 2,
        "HCCOST": 169,
        "COSTPERDOSE": 118,
        "PAYERID": 3
      }, {
        "DRUGID": 23,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "daptomycin",
        "DOSE": 500,
        "TIER": 4,
        "HCCOST": 267,
        "COSTPERDOSE": 129,
        "PAYERID": 3
      }, {
        "DRUGID": 24,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "invanz",
        "DOSE": 500,
        "TIER": 3,
        "HCCOST": 53,
        "COSTPERDOSE": 219,
        "PAYERID": 3
      }, {
        "DRUGID": 25,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "meropenem",
        "DOSE": 1000,
        "TIER": 4,
        "HCCOST": 362,
        "COSTPERDOSE": 89,
        "PAYERID": 3
      }, {
        "DRUGID": 26,
        "DRUGTYPE": "enternal_nutrition",
        "DRUGNAME": "ensure",
        "DOSE": 500,
        "TIER": 1,
        "HCCOST": 174,
        "COSTPERDOSE": 33,
        "PAYERID": 3
      }, {
        "DRUGID": 27,
        "DRUGTYPE": "enternal_nutrition",
        "DRUGNAME": "vivonex 10",
        "DOSE": 500,
        "TIER": 3,
        "HCCOST": 365,
        "COSTPERDOSE": 45,
        "PAYERID": 3
      }, {
        "DRUGID": 28,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "vancomycin",
        "DOSE": 500,
        "TIER": 2,
        "HCCOST": 286,
        "COSTPERDOSE": 27,
        "PAYERID": 4
      }, {
        "DRUGID": 29,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "rocephin",
        "DOSE": 500,
        "TIER": 2,
        "HCCOST": 276,
        "COSTPERDOSE": 106,
        "PAYERID": 4
      }, {
        "DRUGID": 30,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "cefepime",
        "DOSE": 500,
        "TIER": 3,
        "HCCOST": 350,
        "COSTPERDOSE": 222,
        "PAYERID": 4
      }, {
        "DRUGID": 31,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "zosyn",
        "DOSE": 1000,
        "TIER": 2,
        "HCCOST": 169,
        "COSTPERDOSE": 197,
        "PAYERID": 4
      }, {
        "DRUGID": 32,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "daptomycin",
        "DOSE": 500,
        "TIER": 4,
        "HCCOST": 267,
        "COSTPERDOSE": 85,
        "PAYERID": 4
      }, {
        "DRUGID": 33,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "invanz",
        "DOSE": 500,
        "TIER": 3,
        "HCCOST": 53,
        "COSTPERDOSE": 177,
        "PAYERID": 4
      }, {
        "DRUGID": 34,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "meropenem",
        "DOSE": 1000,
        "TIER": 4,
        "HCCOST": 362,
        "COSTPERDOSE": 166,
        "PAYERID": 4
      }, {
        "DRUGID": 35,
        "DRUGTYPE": "enternal_nutrition",
        "DRUGNAME": "ensure",
        "DOSE": 500,
        "TIER": 1,
        "HCCOST": 174,
        "COSTPERDOSE": 155,
        "PAYERID": 4
      }, {
        "DRUGID": 36,
        "DRUGTYPE": "enternal_nutrition",
        "DRUGNAME": "vivonex 10",
        "DOSE": 500,
        "TIER": 3,
        "HCCOST": 365,
        "COSTPERDOSE": 144,
        "PAYERID": 4
      }, {
        "DRUGID": 37,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "vancomycin",
        "DOSE": 500,
        "TIER": 2,
        "HCCOST": 286,
        "COSTPERDOSE": 66,
        "PAYERID": 5
      }, {
        "DRUGID": 38,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "rocephin",
        "DOSE": 500,
        "TIER": 2,
        "HCCOST": 276,
        "COSTPERDOSE": 155,
        "PAYERID": 5
      }, {
        "DRUGID": 39,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "cefepime",
        "DOSE": 500,
        "TIER": 3,
        "HCCOST": 350,
        "COSTPERDOSE": 189,
        "PAYERID": 5
      }, {
        "DRUGID": 40,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "zosyn",
        "DOSE": 1000,
        "TIER": 2,
        "HCCOST": 169,
        "COSTPERDOSE": 25,
        "PAYERID": 5
      }, {
        "DRUGID": 41,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "daptomycin",
        "DOSE": 500,
        "TIER": 4,
        "HCCOST": 267,
        "COSTPERDOSE": 33,
        "PAYERID": 5
      }, {
        "DRUGID": 42,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "invanz",
        "DOSE": 500,
        "TIER": 3,
        "HCCOST": 53,
        "COSTPERDOSE": 51,
        "PAYERID": 5
      }, {
        "DRUGID": 43,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "meropenem",
        "DOSE": 1000,
        "TIER": 4,
        "HCCOST": 362,
        "COSTPERDOSE": 63,
        "PAYERID": 5
      }, {
        "DRUGID": 44,
        "DRUGTYPE": "enternal_nutrition",
        "DRUGNAME": "ensure",
        "DOSE": 500,
        "TIER": 1,
        "HCCOST": 174,
        "COSTPERDOSE": 84,
        "PAYERID": 5
      }, {
        "DRUGID": 45,
        "DRUGTYPE": "enternal_nutrition",
        "DRUGNAME": "vivonex 10",
        "DOSE": 500,
        "TIER": 3,
        "HCCOST": 365,
        "COSTPERDOSE": 174,
        "PAYERID": 5
      }, {
        "DRUGID": 46,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "vancomycin",
        "DOSE": 500,
        "TIER": 2,
        "HCCOST": 286,
        "COSTPERDOSE": 83,
        "PAYERID": 6
      }, {
        "DRUGID": 47,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "rocephin",
        "DOSE": 500,
        "TIER": 2,
        "HCCOST": 276,
        "COSTPERDOSE": 75,
        "PAYERID": 6
      }, {
        "DRUGID": 48,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "cefepime",
        "DOSE": 500,
        "TIER": 3,
        "HCCOST": 350,
        "COSTPERDOSE": 144,
        "PAYERID": 6
      }, {
        "DRUGID": 49,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "zosyn",
        "DOSE": 1000,
        "TIER": 2,
        "HCCOST": 169,
        "COSTPERDOSE": 230,
        "PAYERID": 6
      }, {
        "DRUGID": 50,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "daptomycin",
        "DOSE": 500,
        "TIER": 4,
        "HCCOST": 267,
        "COSTPERDOSE": 51,
        "PAYERID": 6
      }, {
        "DRUGID": 51,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "invanz",
        "DOSE": 500,
        "TIER": 3,
        "HCCOST": 53,
        "COSTPERDOSE": 26,
        "PAYERID": 6
      }, {
        "DRUGID": 52,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "meropenem",
        "DOSE": 1000,
        "TIER": 4,
        "HCCOST": 362,
        "COSTPERDOSE": 71,
        "PAYERID": 6
      }, {
        "DRUGID": 53,
        "DRUGTYPE": "enternal_nutrition",
        "DRUGNAME": "ensure",
        "DOSE": 500,
        "TIER": 1,
        "HCCOST": 174,
        "COSTPERDOSE": 38,
        "PAYERID": 6
      }, {
        "DRUGID": 54,
        "DRUGTYPE": "enternal_nutrition",
        "DRUGNAME": "vivonex 10",
        "DOSE": 500,
        "TIER": 3,
        "HCCOST": 365,
        "COSTPERDOSE": 99,
        "PAYERID": 6
      }, {
        "DRUGID": 55,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "vancomycin",
        "DOSE": 500,
        "TIER": 2,
        "HCCOST": 286,
        "COSTPERDOSE": 105,
        "PAYERID": 7
      }, {
        "DRUGID": 56,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "rocephin",
        "DOSE": 500,
        "TIER": 2,
        "HCCOST": 276,
        "COSTPERDOSE": 204,
        "PAYERID": 7
      }, {
        "DRUGID": 57,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "cefepime",
        "DOSE": 500,
        "TIER": 3,
        "HCCOST": 350,
        "COSTPERDOSE": 69,
        "PAYERID": 7
      }, {
        "DRUGID": 58,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "zosyn",
        "DOSE": 1000,
        "TIER": 2,
        "HCCOST": 169,
        "COSTPERDOSE": 40,
        "PAYERID": 7
      }, {
        "DRUGID": 59,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "daptomycin",
        "DOSE": 500,
        "TIER": 4,
        "HCCOST": 267,
        "COSTPERDOSE": 39,
        "PAYERID": 7
      }, {
        "DRUGID": 60,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "invanz",
        "DOSE": 500,
        "TIER": 3,
        "HCCOST": 53,
        "COSTPERDOSE": 222,
        "PAYERID": 7
      }, {
        "DRUGID": 61,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "meropenem",
        "DOSE": 1000,
        "TIER": 4,
        "HCCOST": 362,
        "COSTPERDOSE": 155,
        "PAYERID": 7
      }, {
        "DRUGID": 62,
        "DRUGTYPE": "enternal_nutrition",
        "DRUGNAME": "ensure",
        "DOSE": 500,
        "TIER": 1,
        "HCCOST": 174,
        "COSTPERDOSE": 82,
        "PAYERID": 7
      }, {
        "DRUGID": 63,
        "DRUGTYPE": "enternal_nutrition",
        "DRUGNAME": "vivonex 10",
        "DOSE": 500,
        "TIER": 3,
        "HCCOST": 365,
        "COSTPERDOSE": 191,
        "PAYERID": 7
      }, {
        "DRUGID": 64,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "vancomycin",
        "DOSE": 500,
        "TIER": 2,
        "HCCOST": 286,
        "COSTPERDOSE": 82,
        "PAYERID": 8
      }, {
        "DRUGID": 65,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "rocephin",
        "DOSE": 500,
        "TIER": 2,
        "HCCOST": 276,
        "COSTPERDOSE": 96,
        "PAYERID": 8
      }, {
        "DRUGID": 66,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "cefepime",
        "DOSE": 500,
        "TIER": 3,
        "HCCOST": 350,
        "COSTPERDOSE": 144,
        "PAYERID": 8
      }, {
        "DRUGID": 67,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "zosyn",
        "DOSE": 1000,
        "TIER": 2,
        "HCCOST": 169,
        "COSTPERDOSE": 211,
        "PAYERID": 8
      }, {
        "DRUGID": 68,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "daptomycin",
        "DOSE": 500,
        "TIER": 4,
        "HCCOST": 267,
        "COSTPERDOSE": 191,
        "PAYERID": 8
      }, {
        "DRUGID": 69,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "invanz",
        "DOSE": 500,
        "TIER": 3,
        "HCCOST": 53,
        "COSTPERDOSE": 50,
        "PAYERID": 8
      }, {
        "DRUGID": 70,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "meropenem",
        "DOSE": 1000,
        "TIER": 4,
        "HCCOST": 362,
        "COSTPERDOSE": 103,
        "PAYERID": 8
      }, {
        "DRUGID": 71,
        "DRUGTYPE": "enternal_nutrition",
        "DRUGNAME": "ensure",
        "DOSE": 500,
        "TIER": 1,
        "HCCOST": 174,
        "COSTPERDOSE": 171,
        "PAYERID": 8
      }, {
        "DRUGID": 72,
        "DRUGTYPE": "enternal_nutrition",
        "DRUGNAME": "vivonex 10",
        "DOSE": 500,
        "TIER": 3,
        "HCCOST": 365,
        "COSTPERDOSE": 194,
        "PAYERID": 8
      }, {
        "DRUGID": 73,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "vancomycin",
        "DOSE": 500,
        "TIER": 2,
        "HCCOST": 286,
        "COSTPERDOSE": 84,
        "PAYERID": 9
      }, {
        "DRUGID": 74,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "rocephin",
        "DOSE": 500,
        "TIER": 2,
        "HCCOST": 276,
        "COSTPERDOSE": 223,
        "PAYERID": 9
      }, {
        "DRUGID": 75,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "cefepime",
        "DOSE": 500,
        "TIER": 3,
        "HCCOST": 350,
        "COSTPERDOSE": 111,
        "PAYERID": 9
      }, {
        "DRUGID": 76,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "zosyn",
        "DOSE": 1000,
        "TIER": 2,
        "HCCOST": 169,
        "COSTPERDOSE": 103,
        "PAYERID": 9
      }, {
        "DRUGID": 77,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "daptomycin",
        "DOSE": 500,
        "TIER": 4,
        "HCCOST": 267,
        "COSTPERDOSE": 200,
        "PAYERID": 9
      }, {
        "DRUGID": 78,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "invanz",
        "DOSE": 500,
        "TIER": 3,
        "HCCOST": 53,
        "COSTPERDOSE": 188,
        "PAYERID": 9
      }, {
        "DRUGID": 79,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "meropenem",
        "DOSE": 1000,
        "TIER": 4,
        "HCCOST": 362,
        "COSTPERDOSE": 155,
        "PAYERID": 9
      }, {
        "DRUGID": 80,
        "DRUGTYPE": "enternal_nutrition",
        "DRUGNAME": "ensure",
        "DOSE": 500,
        "TIER": 1,
        "HCCOST": 174,
        "COSTPERDOSE": 134,
        "PAYERID": 9
      }, {
        "DRUGID": 81,
        "DRUGTYPE": "enternal_nutrition",
        "DRUGNAME": "vivonex 10",
        "DOSE": 500,
        "TIER": 3,
        "HCCOST": 365,
        "COSTPERDOSE": 26,
        "PAYERID": 9
      }, {
        "DRUGID": 82,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "vancomycin",
        "DOSE": 500,
        "TIER": 2,
        "HCCOST": 286,
        "COSTPERDOSE": 244,
        "PAYERID": 10
      }, {
        "DRUGID": 83,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "rocephin",
        "DOSE": 500,
        "TIER": 2,
        "HCCOST": 276,
        "COSTPERDOSE": 249,
        "PAYERID": 10
      }, {
        "DRUGID": 84,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "cefepime",
        "DOSE": 500,
        "TIER": 3,
        "HCCOST": 350,
        "COSTPERDOSE": 133,
        "PAYERID": 10
      }, {
        "DRUGID": 85,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "zosyn",
        "DOSE": 1000,
        "TIER": 2,
        "HCCOST": 169,
        "COSTPERDOSE": 222,
        "PAYERID": 10
      }, {
        "DRUGID": 86,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "daptomycin",
        "DOSE": 500,
        "TIER": 4,
        "HCCOST": 267,
        "COSTPERDOSE": 111,
        "PAYERID": 10
      }, {
        "DRUGID": 87,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "invanz",
        "DOSE": 500,
        "TIER": 3,
        "HCCOST": 53,
        "COSTPERDOSE": 43,
        "PAYERID": 10
      }, {
        "DRUGID": 88,
        "DRUGTYPE": "antibiotics",
        "DRUGNAME": "meropenem",
        "DOSE": 1000,
        "TIER": 4,
        "HCCOST": 362,
        "COSTPERDOSE": 177,
        "PAYERID": 10
      }, {
        "DRUGID": 89,
        "DRUGTYPE": "enternal_nutrition",
        "DRUGNAME": "ensure",
        "DOSE": 500,
        "TIER": 1,
        "HCCOST": 174,
        "COSTPERDOSE": 165,
        "PAYERID": 10
      }, {
        "DRUGID": 90,
        "DRUGTYPE": "enternal_nutrition",
        "DRUGNAME": "vivonex 10",
        "DOSE": 500,
        "TIER": 3,
        "HCCOST": 365,
        "COSTPERDOSE": 217,
        "PAYERID": 10
      }
    ]);
  });
};
