exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('patients_drugs').del().then(function() {
    // Inserts seed entries
    return knex('patients_drugs').insert([
      {
        "PATIENTID": "PIF-01000001",
        "patientdrugid": 1,
        "DRUGID": 1,
        "DURATION": 0,
        "APPROVED": 1
      }, {
        "PATIENTID": "PIF-01000002",
        "patientdrugid": 2,
        "DRUGID": 2,
        "DURATION": 3,
        "APPROVED": 0
      }, {
        "PATIENTID": "PIF-01000003",
        "patientdrugid": 3,
        "DRUGID": 3,
        "DURATION": 6,
        "APPROVED": -1
      }, {
        "PATIENTID": "PIF-01000004",
        "patientdrugid": 4,
        "DRUGID": 4,
        "DURATION": 8,
        "APPROVED": -1
      }, {
        "PATIENTID": "PIF-01000005",
        "patientdrugid": 5,
        "DRUGID": 5,
        "DURATION": 15,
        "APPROVED": 1
      }, {
        "PATIENTID": "PIF-01000006",
        "patientdrugid": 6,
        "DRUGID": 6,
        "DURATION": 26,
        "APPROVED": 0
      }, {
        "PATIENTID": "PIF-01000007",
        "patientdrugid": 7,
        "DRUGID": 7,
        "DURATION": 24,
        "APPROVED": -1
      }, {
        "PATIENTID": "PIF-01000008",
        "patientdrugid": 8,
        "DRUGID": 8,
        "DURATION": 18,
        "APPROVED": -1
      }, {
        "PATIENTID": "PIF-01000009",
        "patientdrugid": 9,
        "DRUGID": 9,
        "DURATION": 10,
        "APPROVED": 1
      }, {
        "PATIENTID": "PIF-01000010",
        "patientdrugid": 10,
        "DRUGID": 10,
        "DURATION": 14,
        "APPROVED": 0
      }, {
        "PATIENTID": "PIF-01000011",
        "patientdrugid": 11,
        "DRUGID": 11,
        "DURATION": 21,
        "APPROVED": 0
      }, {
        "PATIENTID": "PIF-01000012",
        "patientdrugid": 12,
        "DRUGID": 12,
        "DURATION": 31,
        "APPROVED": 1
      }, {
        "PATIENTID": "PIF-01000013",
        "patientdrugid": 13,
        "DRUGID": 13,
        "DURATION": 22,
        "APPROVED": -1
      }, {
        "PATIENTID": "PIF-01000014",
        "patientdrugid": 14,
        "DRUGID": 14,
        "DURATION": 8,
        "APPROVED": -1
      }, {
        "PATIENTID": "PIF-01000015",
        "patientdrugid": 15,
        "DRUGID": 15,
        "DURATION": 10,
        "APPROVED": 1
      }, {
        "PATIENTID": "PIF-01000016",
        "patientdrugid": 16,
        "DRUGID": 16,
        "DURATION": 17,
        "APPROVED": 1
      }, {
        "PATIENTID": "PIF-01000017",
        "patientdrugid": 17,
        "DRUGID": 17,
        "DURATION": 27,
        "APPROVED": -1
      }, {
        "PATIENTID": "PIF-01000018",
        "patientdrugid": 18,
        "DRUGID": 18,
        "DURATION": 22,
        "APPROVED": 0
      }, {
        "PATIENTID": "PIF-01000019",
        "patientdrugid": 19,
        "DRUGID": 19,
        "DURATION": 16,
        "APPROVED": 0
      }, {
        "PATIENTID": "PIF-01000020",
        "patientdrugid": 20,
        "DRUGID": 20,
        "DURATION": 30,
        "APPROVED": 0
      }, {
        "PATIENTID": "PIF-012345687",
        "patientdrugid": 21,
        "DRUGID": 14,
        "DURATION": 7,
        "APPROVED": -1
      }, {
        "PATIENTID": "PIF-78920384",
        "patientdrugid": 22,
        "DRUGID": 17,
        "DURATION": 15,
        "APPROVED": -1
      }
    ]);
  });
};
